//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFEM_Software.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RFEM_Software.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              xmlns:local=&quot;clr-namespace:RFEM_Software.Help_Files&quot;
        ///              ColumnWidth=&quot;400&quot; FontSize=&quot;14&quot; FontFamily=&quot;Georgia&quot;&gt;
        ///    &lt;Paragraph&gt;
        ///        THE RANDOM FINITE ELEMENT METHOD
        ///
        ///                            Software Version 1.0.0
        ///
        ///                                 Written by
        ///
        ///Professors:	Dr. Gordon A. Fenton	Dr. D.V. Griffiths
        ///Email:		Gordon.Fenton@dal.ca	d.v.griffiths@mines.edu
        ///Phone:		902-494-6002		303 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppHelp {
            get {
                return ResourceManager.GetString("AppHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              xmlns:local=&quot;clr-namespace:RFEM_Software.Help_Files.RBear_Help_Files&quot;
        ///              ColumnWidth=&quot;400&quot; FontSize=&quot;14&quot; FontFamily=&quot;Georgia&quot;&gt;
        ///    &lt;Paragraph&gt;
        ///        Enabling this option causes the input data provided on this form to be
        ///echoed to the output *.stt file. This is useful both to check the data
        ///and to associate the run parameters with the output files.
        ///    &lt;/Paragraph&gt;
        ///&lt;/FlowDocument&gt;
        ///.
        /// </summary>
        internal static string EchoInputToOutputFile {
            get {
                return ResourceManager.GetString("EchoInputToOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help_2 {
            get {
                object obj = ResourceManager.GetObject("Help_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       THE RANDOM FINITE ELEMENT METHOD
        ///
        ///                            Software Version 1.0.0
        ///
        ///                                 Written by
        ///
        ///Professors:	Dr. Gordon A. Fenton	Dr. D.V. Griffiths
        ///Email:		Gordon.Fenton@dal.ca	d.v.griffiths@mines.edu
        ///Phone:		902-494-6002		303-273-3669
        ///Location:	Dalhousie University	Colorado School of Mines
        ///		Halifax, Canada		Golden, Colorado
        ///
        ///In 1992 Drs. G.A. Fenton and D.V. Griffiths combined random field simulation
        ///with the finite element method to pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainHelp {
            get {
                return ResourceManager.GetString("MainHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              xmlns:local=&quot;clr-namespace:RFEM_Software.Help_Files.RBear_Help_Files&quot;
        ///              ColumnWidth=&quot;400&quot; FontSize=&quot;14&quot; FontFamily=&quot;Georgia&quot;&gt;
        ///    &lt;Paragraph&gt;
        ///        Enabling this option results in one of the random soil property
        ///    fields to be shown as a greyscale image on the bearing failure plot.
        ///    Low field values are shown in white.
        ///    This option is followed by two other options: The first controls
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PropertyToPlot {
            get {
                return ResourceManager.GetString("PropertyToPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              xmlns:local=&quot;clr-namespace:RFEM_Software.Help_Files.RBear_Help_Files&quot;
        ///              ColumnWidth=&quot;400&quot; FontSize=&quot;14&quot; FontFamily=&quot;Georgia&quot;&gt;
        ///    &lt;Paragraph&gt;
        ///        RBEAR2D(1)
        ///
        ///NAME
        ///  rbear2d - computes bearing capacity statistics in a soil with spatially
        ///            random properties
        ///
        ///SYNOPSIS
        ///  rbear2d datafile
        ///
        ///DESCRIPTION
        ///  This program performs a bearing capacity stochastic analysis of a soil
        ///  mas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RBear2dHelp {
            get {
                return ResourceManager.GetString("RBear2dHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              xmlns:local=&quot;clr-namespace:RFEM_Software.Help_Files.RBear_Help_Files&quot;
        ///              ColumnWidth=&quot;400&quot; FontSize=&quot;14&quot; FontFamily=&quot;Georgia&quot;&gt;
        ///    &lt;Paragraph&gt;
        ///        Enabling this option results in one of the random soil property
        ///    fields to be shown as a greyscale image on the bearing failure plot.
        ///    Low field values are shown in white.
        ///    This option is followed by two other options: The first controls
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShowLogRF {
            get {
                return ResourceManager.GetString("ShowLogRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              xmlns:local=&quot;clr-namespace:RFEM_Software.Help_Files.RBear_Help_Files&quot;
        ///              ColumnWidth=&quot;400&quot; FontSize=&quot;14&quot; FontFamily=&quot;Georgia&quot;
        ///              &gt;
        ///       
        ///    &lt;Paragraph&gt;
        ///            Enabling this option results in one of the random soil property
        ///    fields to be shown as a greyscale image on the bearing failure plot.
        ///    Low field values are shown in white.
        ///    This option is followed by two other o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShowRFOnDisplacedMeshPlot {
            get {
                return ResourceManager.GetString("ShowRFOnDisplacedMeshPlot", resourceCulture);
            }
        }
    }
}
